//47
// Version.tt v2.0.2.1
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.2.9.47")]
[assembly: AssemblyVersion("1.2.9.9")]
[assembly: AssemblyInformationalVersion("v1.2.9")]
[assembly: KSPAssembly("KspChromaControl", 1,2,9)]

namespace KspChromaControl
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 2;
		public const int patch = 9;
		public const int build = 9;
		public const string Number = "1.2.9.9";
#if DEBUG
        public const string Text = Number + "-zed'K BETA DEBUG";
#else
        public const string Text = Number + "-zed'K";
#endif
	}
}