//13
// Version.tt v2.0.2.1
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.12.0.13")]
[assembly: AssemblyVersion("1.12.0.0")]
[assembly: AssemblyInformationalVersion("v1.12.0")]
[assembly: KSPAssembly("KspChromaControl", 1,12,0)]

namespace KspChromaControl
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 12;
		public const int patch = 0;
		public const int build = 0;
		public const string Number = "1.12.0.0";
#if DEBUG
        public const string Text = Number + "-zed'K BETA DEBUG";
#else
        public const string Text = Number + "-zed'K";
#endif
	}
}