<<<<<<< Updated upstream
﻿//52
=======
﻿//68
>>>>>>> Stashed changes
// Version.tt v2.0.2.1
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

<<<<<<< Updated upstream
[assembly: AssemblyFileVersion("1.2.9.52")]
[assembly: AssemblyVersion("1.2.9.9")]
[assembly: AssemblyInformationalVersion("v1.2.9")]
[assembly: KSPAssembly("KspChromaControl", 1,2,9)]
=======
[assembly: AssemblyFileVersion("1.2.99.68")]
[assembly: AssemblyVersion("1.2.99.0")]
[assembly: AssemblyInformationalVersion("v1.2.99")]
[assembly: KSPAssembly("KspChromaControl", 1,2,99)]
>>>>>>> Stashed changes

namespace KspChromaControl
{
	public static class Version
	{
		public const int major = 1;
		public const int minor = 2;
<<<<<<< Updated upstream
		public const int patch = 9;
		public const int build = 9;
		public const string Number = "1.2.9.9";
=======
		public const int patch = 99;
		public const int build = 0;
		public const string Number = "1.2.99.0";
>>>>>>> Stashed changes
#if DEBUG
        public const string Text = Number + "-zed'K BETA DEBUG";
#else
        public const string Text = Number + "-zed'K";
#endif
	}
}